# Generated by Django 2.0.9 on 2025-11-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
    ]
