# Generated by Django 2.0.9 on 2025-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20251128_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
