# Generated by Django 2.0.9 on 2025-12-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='staff',
        ),
    ]
