# Generated by Django 2.0.9 on 2025-12-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_remove_feedback_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
