# Generated by Django 2.0.9 on 2025-12-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_booking_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returnproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Booking')),
            ],
        ),
    ]
