# Generated by Django 2.0.9 on 2025-12-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_returnproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_app.Booking'),
            preserve_default=False,
        ),
    ]
